### ISSUE TITLE
Sivupohjiin raatilaissidebarit sopiville sivuille

### ISSUE THREAD

**Issue by summis** [fyysikkokilta/fktheme2019#12]

**Comment by Alphenus** [comment]
Tähän on pohja ja ohje siis seuraava:

**Raatilaisten lisääminen sivupalkkiin**:
- Valitse muokattavaksesi sivu, johon haluat lisätä raatilaisen pärstän
- Editorin oikeassa reunassa klikkaa Sivun ominaisuudet (Asiakirja-tabilla) -> sivupohja -> Raatilais-sidebar
- Julkaise/päivitä julkaisu
- Päivitä sivu (ctrl+r, F5 tai jotain sellaista)
- Alareunaan pitäis ilmestyä "Raatilais-sidebar" -kenttä, jossa voit valita raatilaisen. 
- Julkaise/päivitä julkaisu uudestaan
- Pro fit
disclaimer: en ole tämän leiskalle ehtinyt tekemään mitään, joten se muuttunnee nätimmäksi aikojen saatossa

**Comment by summis** [comment]
Dun
