### ISSUE TITLE
Yhtenäinen layout kaikkien artikkeleiden väliotsikoille

### ISSUE THREAD

**Issue by summis** [fyysikkokilta/fktheme2019#13]
Nyt fontti ja koko vähän vaihtelee eri artsuissa, tarvii graafikon ratkaisua siitä mikä on parhaiten sopiva tyyli ja käyttää sitä joka kohdassa

**Comment by Alphenus** [comment]
Hyvä pointti! Voin pakottaa sen laittamalla kaikki otsikkokoot tekstin sisällä saman kokoisiksi, olisiko se hyvä ratkaisu? Silloin toki ei voisi mitenkään laittaa eri kokoisia otsikoita, mutta se ei ehkä ole tarpeen?

**Comment by summis** [comment]
Ehkä joku kiltajärjestyksen kaltainen teksti hyötyy siitä voi käyttää erottuvia h2, h3 ja h4 otsikoita, koska siinä on paljon alakohtia. En välttis kaikkia saman kokoisiksi pakottaisi :thinking: 
Enemmän ehkä siihen kiinnitin huomiota että esim "Fuksina killassa" ja "Tiedotuskanavat" artsuilla on eri tyyliset otsikot, niihin pitäis saada samat

**Comment by Alphenus** [comment]
Ratkaisuna on käyttää kaikilla sivuilla alaotsikkona 'Otsikko' -blokkia, eikä käsin kasvattaa tekstin kokoa.
