### ISSUE TITLE
URLit muuttuu käännöksen yhteydessä

### ISSUE THREAD

**Issue by summis** [fyysikkokilta/fktheme2019#14]
Kun painaa "Julkaise" tarkastettavana olevalle käännetylle artikkelille, näyttää siltä, että wp muuttaa sen URL-osoitteen. Esim. Jäseneksi-sivu on nyt https://www.fyysikkokilta.fi/dev/membership/

**Comment by summis** [comment]
Jos sitä koittaa muuttaa manuaalisesti artikkelista niin se menee toiseen suuntaan fak:
https://www.fyysikkokilta.fi/dev/en/jaseneksi/

**Comment by Alphenus** [comment]
Hmm "WP Multilang do not support multilingual slugs in base version." (https://wordpress.org/support/topic/permalink-translation/). Tjaa'a.
