### ISSUE TITLE
Englanninkielisessä menussa pitkät tekstit rivittyvät kahdelle riville

### ISSUE THREAD

**Issue by summis** [fyysikkokilta/fktheme2019#16]
Ehkä jos noi saisi ylhäältä tasattua samalle tasolle voisi näyttää kivemmalta

**Comment by Alphenus** [comment]
Fiksasin tuon nyt estämällä rivittymisen kokonaan. Pitää kuitenkin pitää järki kädessä menu-itemeiden määrässä ja nimien pituudessa.
