### ISSUE TITLE
Lisää Telegram-nickit raatikuvien oheen

### ISSUE THREAD

**Issue by summis** [fyysikkokilta/fktheme2019#9]

**Comment by Alphenus** [comment]
TG-nickeille on nyt paikat Raatilais-sivuilla. Sivut tukee nyt myös englantia, joten tittelit voisi kääntää myöskin @summis .

**Comment by summis** [comment]
Joo, otan työn alle :+1:

**Comment by summis** [comment]
Noi nickit ei vielä ole näkyvissä itse sivulla, listätty on kyllä

**Comment by Alphenus** [comment]
Nyt on TG-nickit kanssa näkyvissä.
